-- ============================================================
-- Recipe Agent Schema
-- Migration 002 — depends on 001_schema.sql
-- ============================================================

-- ============================================================
-- RECIPE PROFILES
-- One row per user; stores all preference/goal data passed
-- to the Claude agent as system context.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.recipe_profiles (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    -- Dietary restrictions / allergies (e.g. ["vegan", "gluten-free", "nut allergy"])
    dietary_needs   TEXT[]    NOT NULL DEFAULT '{}',
    -- Cuisine and flavor preferences (e.g. ["mediterranean", "spicy"])
    preferences     TEXT[]    NOT NULL DEFAULT '{}',
    -- Health / goal tags (e.g. ["weight loss", "high protein", "low sodium"])
    goals           TEXT[]    NOT NULL DEFAULT '{}',
    -- Preferred recipe source sites (e.g. ["seriouseats.com", "budgetbytes.com"])
    preferred_sites TEXT[]    NOT NULL DEFAULT '{}',
    -- Subscription sites the user has access to
    subscription_sites TEXT[] NOT NULL DEFAULT '{}',
    -- Free-form additional context for the agent
    additional_notes TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id)
);

CREATE INDEX IF NOT EXISTS recipe_profiles_user_id_idx
    ON public.recipe_profiles (user_id);

-- ============================================================
-- RECIPES
-- Saved recipes from agent results.
-- source_url is nullable for manually entered recipes.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.recipes (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    title           TEXT NOT NULL,
    description     TEXT,
    ingredients     JSONB NOT NULL DEFAULT '[]',
    -- Each step is a string
    directions      JSONB NOT NULL DEFAULT '[]',
    prep_time_mins  INTEGER,
    cook_time_mins  INTEGER,
    servings        INTEGER,
    source_url      TEXT,
    image_url       TEXT,
    -- Auto-generated by agent + manually editable
    tags            TEXT[]   NOT NULL DEFAULT '{}',
    -- 1-5 star rating; null = unrated
    rating          SMALLINT CHECK (rating >= 1 AND rating <= 5),
    is_favorite     BOOLEAN  NOT NULL DEFAULT FALSE,
    -- 'want_to_try' | 'tasted'
    tasted_status   TEXT     CHECK (tasted_status IN ('want_to_try', 'tasted')),
    notes           TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS recipes_user_id_idx
    ON public.recipes (user_id);
CREATE INDEX IF NOT EXISTS recipes_is_favorite_idx
    ON public.recipes (user_id, is_favorite);
CREATE INDEX IF NOT EXISTS recipes_rating_idx
    ON public.recipes (user_id, rating);
-- GIN index for fast tag array searching
CREATE INDEX IF NOT EXISTS recipes_tags_gin_idx
    ON public.recipes USING gin (tags);

-- ============================================================
-- RECIPE SEARCH HISTORY
-- Stored so we can show recent searches in the UI.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.recipe_searches (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    query       TEXT NOT NULL,
    searched_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS recipe_searches_user_id_idx
    ON public.recipe_searches (user_id, searched_at DESC);

-- ============================================================
-- UPDATED_AT TRIGGER
-- ============================================================

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER recipe_profiles_updated_at
    BEFORE UPDATE ON public.recipe_profiles
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER recipes_updated_at
    BEFORE UPDATE ON public.recipes
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE public.recipe_profiles     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipes             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipe_searches     ENABLE ROW LEVEL SECURITY;

-- recipe_profiles: each user owns their own row
CREATE POLICY "Users manage own recipe profile"
    ON public.recipe_profiles FOR ALL
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

-- recipes: each user owns their own rows; admins can see all
CREATE POLICY "Users manage own recipes"
    ON public.recipes FOR ALL
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

CREATE POLICY "Admins can view all recipes"
    ON public.recipes FOR SELECT
    USING (public.is_admin());

-- recipe_searches: private per user
CREATE POLICY "Users manage own search history"
    ON public.recipe_searches FOR ALL
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());
