import type { AgentStreamEvent } from '@true-tech-team/agent-kit';

// ---- Canonical resume data shape ----
// Shared by every one of the 20 template components, the fill agent, and the
// critique agent. Get this exactly right — everything else in the feature
// depends on it.

export interface ResumeProfile {
  name: string;
  title: string;
  phone: string;
  email: string;
  location: string;
  linkedin?: string;
  website?: string;
}

export interface ResumeSkillGroup {
  category: string;
  items: string[];
}

export interface ResumeExperienceEntry {
  company: string;
  role: string;
  location: string;
  startDate: string;
  endDate: string;
  bullets: string[];
}

export interface ResumeEducationEntry {
  school: string;
  degree: string;
  location?: string;
  startDate?: string;
  endDate?: string;
}

export interface ResumeCertification {
  title: string;
  issuer: string;
  date?: string;
}

export interface ResumeData {
  profile: ResumeProfile;
  summary: string;
  skills: ResumeSkillGroup[];
  experience: ResumeExperienceEntry[];
  education: ResumeEducationEntry[];
  certifications?: ResumeCertification[];
}

// The fill agent, when parsing an uploaded resume (not when improving an
// existing draft or tailoring toward a job), also infers a starting point
// for Job Search preferences — a bonus field alongside the normal
// ResumeData shape, not part of it. See buildFillSystemPrompt's uploadedText
// branch, and lib/resumeImport.ts's mapSuggestedSearchPreferences.
export interface SuggestedSearchPreferences {
  targetTitle?: string;
  industry?: string;
  experienceLevel?: 'entry' | 'mid' | 'senior' | 'lead';
  skillsFocus?: string;
}

export interface ResumeDataWithSuggestions extends ResumeData {
  suggestedSearchPreferences?: SuggestedSearchPreferences;
}

// ---- Resume document (DB row) ----

export interface ResumeDocument {
  id: string;
  userId: string;
  name: string;
  templateId: string;
  data: ResumeData;
  // Lineage — set when this document was generated by tailoring another
  // saved resume toward a specific job (see the resume-builder/customize
  // route); both null for a normally-created resume.
  sourceDocumentId: string | null;
  jobSearchJobId: string | null;
  createdAt: string;
  updatedAt: string;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function mapDocumentRow(row: Record<string, any>): ResumeDocument {
  return {
    id: row['id'] as string,
    userId: row['user_id'] as string,
    name: row['name'] as string,
    templateId: row['template_id'] as string,
    data: (row['data'] as ResumeData) ?? ({} as ResumeData),
    sourceDocumentId: (row['source_document_id'] as string | null) ?? null,
    jobSearchJobId: (row['job_search_job_id'] as string | null) ?? null,
    createdAt: row['created_at'] as string,
    updatedAt: row['updated_at'] as string,
  };
}

// ---- Resume critique (agent output shape) ----
// Structured, recruiter-facing feedback produced by the critique agent.

export interface ResumeCritique {
  overallScore: number;
  strengths: string[];
  weaknesses: string[];
  suggestions: string[];
  keywordGaps?: string[];
}

// ---- Resume critique (DB row) ----

export interface ResumeCritiqueRecord {
  id: string;
  userId: string;
  resumeDocumentId: string | null;
  targetJobDescription: string | null;
  feedback: ResumeCritique;
  createdAt: string;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function mapCritiqueRow(row: Record<string, any>): ResumeCritiqueRecord {
  return {
    id: row['id'] as string,
    userId: row['user_id'] as string,
    resumeDocumentId: (row['resume_document_id'] as string | null) ?? null,
    targetJobDescription: (row['target_job_description'] as string | null) ?? null,
    feedback: (row['feedback'] as ResumeCritique) ?? ({} as ResumeCritique),
    createdAt: row['created_at'] as string,
  };
}

// ---- API payload types ----

export interface CreateDocumentPayload {
  name: string;
  templateId: string;
  data: ResumeData;
}

export interface UpdateDocumentPayload {
  name?: string;
  templateId?: string;
  data?: ResumeData;
}

// ---- Stream event types (newline-delimited JSON) ----
// Both resume agents are pure single-turn JSON generators built directly on
// agent-kit's `runAgentLoop` with no tools (no `tool_use`/`tool_result` will
// ever actually fire for either). Rather than add a redundant domain-specific
// remapping layer (as `src/lib/recipes/agent.ts` does, because it has real
// tool events to relabel), both resume agents re-export agent-kit's generic
// `AgentStreamEvent<TResult>` unchanged, specialized to their own result
// type. Whoever builds the frontend NDJSON consumer should switch on these
// exactly like `AgentStreamRenderer.tsx` does for recipes, just reading
// `event.result` (a `ResumeData` or `ResumeCritique`) instead of
// `event.recipe`.
export type ResumeFillStreamEvent = AgentStreamEvent<ResumeData>;
export type ResumeCritiqueStreamEvent = AgentStreamEvent<ResumeCritique>;

// The customize route runs the same fill agent internally, but its persistence
// wrapper remaps the 'result' event's payload from raw ResumeData to the
// newly-created ResumeDocument (the frontend needs the new id to navigate to
// its preview/print page — see customize/route.ts).
export type ResumeCustomizeStreamEvent = AgentStreamEvent<ResumeDocument>;
